FROM python:latest

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements_enviar_email.txt

CMD ["python", "enviar_email.py"]
RUN rm -rf /var/lib/apt/lists/* /root/.cache
