FROM python:3

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements_pagar.txt

CMD ["python", "pagar.py"]
RUN rm -rf /var/lib/apt/lists/* /root/.cache
