version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  pagar-app:
    build:
      context: .
      dockerfile: Dockerfile_pagar
    command: ["python", "pagar.py"]
    depends_on:
      - kafka

  enviar-email-app:
    build:
      context: .
      dockerfile: Dockerfile_enviar_email
    command: ["python", "enviar_email.py"]
    depends_on:
      - kafka

  notificar-app:
    build:
      context: .
      dockerfile: Dockerfile_notificar
    command: ["python", "notificar.py"]
    depends_on:
      - kafka
